; G-Code generated by Simplify3D(R) Version 3.1.0
; Nov 6, 2016 at 7:19:14 PM
; Settings Summary
;   processName,Process1
;   applyToModels,Dæk med runding
;   profileName,MM2PLA (modified)
;   profileVersion,2016-11-05 15:37:44
;   baseProfile,
;   printMaterial,PLA
;   printQuality,High
;   printExtruders,
;   extruderName,Primary Extruder
;   extruderToolheadNumber,0
;   extruderDiameter,0.6
;   extruderAutoWidth,1
;   extruderWidth,0.72
;   extrusionMultiplier,1
;   extruderUseRetract,1
;   extruderRetractionDistance,0.5
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,0.25
;   extruderRetractionSpeed,1800
;   extruderUseCoasting,0
;   extruderCoastingDistance,0.2
;   extruderUseWipe,0
;   extruderWipeDistance,5
;   primaryExtruder,0
;   layerHeight,0.3
;   topSolidLayers,6
;   bottomSolidLayers,4
;   perimeterOutlines,2
;   printPerimetersInsideOut,1
;   startPointOption,2
;   startPointOriginX,0
;   startPointOriginY,0
;   startPointOriginZ,300
;   sequentialIslands,0
;   spiralVaseMode,0
;   firstLayerHeightPercentage,90
;   firstLayerWidthPercentage,120
;   firstLayerUnderspeed,0.4
;   useRaft,0
;   raftExtruder,0
;   raftLayers,3
;   raftOffset,3
;   raftSeparationDistance,0.05
;   raftInfill,85
;   disableRaftBaseLayers,0
;   useSkirt,0
;   skirtExtruder,0
;   skirtLayers,2
;   skirtOutlines,6
;   skirtOffset,0
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,2
;   oozeShieldOutlines,1
;   oozeShieldSidewallShape,1
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1
;   infillExtruder,0
;   internalInfillPattern,Rectilinear
;   externalInfillPattern,Rectilinear
;   infillPercentage,30
;   outlineOverlapPercentage,15
;   infillExtrusionWidthPercentage,125
;   minInfillLength,5
;   infillLayerInterval,1
;   infillAngles,45,-45
;   overlapInfillAngles,0
;   generateSupport,1
;   supportExtruder,0
;   supportInfillPercentage,30
;   supportExtraInflation,1
;   denseSupportLayers,0
;   denseSupportInfillPercentage,75
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.3
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,4
;   maxOverhangAngle,60
;   supportAngles,0
;   temperatureName,Primary Extruder,Heated Bed
;   temperatureNumber,0,2
;   temperatureSetpointCount,1,1
;   temperatureSetpointLayers,1,1
;   temperatureSetpointTemperatures,200,60
;   temperatureStabilizeAtStartup,1,1
;   temperatureHeatedBed,0,1
;   temperatureRelayBetweenLayers,0,0
;   temperatureRelayBetweenLoops,0,0
;   fanLayers,1,5
;   fanSpeeds,0,60
;   blipFanToFullPower,0
;   adjustSpeedForCooling,1
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,0
;   minFanLayerTime,45
;   maxCoolingFanSpeed,100
;   increaseFanForBridging,0
;   bridgingFanSpeed,100
;   use5D,1
;   relativeEdistances,0
;   allowEaxisZeroing,1
;   independentExtruderAxes,0
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0.1
;   overrideMachineDefinition,1
;   machineTypeOverride,0
;   strokeXoverride,240
;   strokeYoverride,310
;   strokeZoverride,225
;   originOffsetXoverride,0
;   originOffsetYoverride,0
;   originOffsetZoverride,0
;   homeXdirOverride,-1
;   homeYdirOverride,-1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,0
;   firmwareTypeOverride,RepRap (Marlin/Repetier/Sprinter)
;   GPXconfigOverride,r2
;   baudRateOverride,115200
;   overridePrinterModels,0
;   printerModelsOverride
;   startingGcode,G28 X0 Y0  ;move X/Y to min endstops,G1 Z15.0 F{travel_speed} ;move the platform down 15mm,G92 E0                  ;zero the extruded length,G1 F200 E20              ;extrude 3mm of feed stock,G92 E0,G1 X20 Y20 F{travel_speed},G28 Z0 
;   layerChangeGcode,
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,M104 S0 ; turn off extruder,M140 S0 ; turn off bed,G28 X0 ; home X axis,M106 S0,M84 ; disable motors,
;   exportFileFormat,gcode
;   celebration,0
;   celebrationSong,Random Song
;   postProcessing,
;   defaultSpeed,4200
;   outlineUnderspeed,0.3
;   solidInfillUnderspeed,0.7
;   supportUnderspeed,0.7
;   rapidXYspeed,9000
;   rapidZspeed,1002
;   minBridgingArea,50
;   bridgingExtraInflation,0
;   bridgingExtrusionMultiplier,1
;   bridgingSpeedMultiplier,1
;   filamentDiameter,1.75
;   filamentPricePerKg,125
;   filamentDensity,1.25
;   useMinPrintHeight,0
;   minPrintHeight,0
;   useMaxPrintHeight,0
;   maxPrintHeight,0
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,0
;   onlyRetractWhenCrossingOutline,1
;   retractBetweenLayers,1
;   useRetractionMinTravel,0
;   retractionMinTravel,3
;   retractWhileWiping,0
;   onlyWipeOutlines,1
;   avoidCrossingOutline,0
;   maxMovementDetourFactor,3
;   toolChangeRetractionDistance,0
;   toolChangeExtraRestartDistance,0
;   toolChangeRetractionSpeed,360
;   allowThinWallGapFill,1
;   thinWallAllowedOverlapPercentage,10
;   horizontalSizeCompensation,0
M84
M84
M84
M84
M84;M84
M84
;M84
M84
M84
; Build Summary
;   Build time: 3 hours 30 minutes
;   Filament length: 54599.6 mm (54.60 m)
;   Plastic volume: 131327.49 mm^3 (131.33 cc)
;   Plastic weight: 164.16 g (0.36 lb)
;   Material cost: 20.52
